# Generated by Django 4.0.5 on 2022-06-10 13:49

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст вопроса')),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='lessons/game', verbose_name='Первое изображение для игры')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='lessons/game', verbose_name='Второе изображение для игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.SlugField(help_text='Если Вы хотите получить URL-адрес вида https://domain/page, тогда просто введите page.', max_length=128, unique=True, verbose_name='Название страницы в URL')),
                ('description', models.TextField(blank=True, help_text='Описание будет использоваться для meta-тега description.', null=True, verbose_name='Описание страницы')),
                ('title', models.CharField(max_length=128, verbose_name='Название урока')),
                ('preview', models.ImageField(upload_to='lessons/preview', verbose_name='Превью-изображение')),
                ('serial_number', models.CharField(help_text='Порядковый номер вида "Урок 1-2".', max_length=32, verbose_name='Порядковый номер')),
                ('background_image', models.ImageField(upload_to='lessons/background', verbose_name='Задний фон урока')),
                ('interesting_img', models.ImageField(upload_to='lessons/interesting', verbose_name='Изображение')),
                ('interesting_text', models.TextField(max_length=4096, verbose_name='Текст')),
                ('fact_img', models.ImageField(upload_to='lessons/fact', verbose_name='Изображение')),
                ('fact_text', models.TextField(max_length=4096, verbose_name='Текст')),
                ('practical_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название практического задания')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст вопроса')),
                ('explanation', ckeditor.fields.RichTextField(max_length=4096, verbose_name='Объяснение к тренажеру')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', related_query_name='trainer', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Тренажер',
                'verbose_name_plural': 'Тренажеры',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=128, verbose_name='Название раздела')),
                ('img_1', models.ImageField(upload_to='units', verbose_name='Изображение 1')),
                ('img_2', models.ImageField(upload_to='units', verbose_name='Изображение 2')),
                ('img_3', models.ImageField(upload_to='units', verbose_name='Изображение 3')),
                ('serial_number', models.PositiveIntegerField(unique=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ('serial_number',),
            },
        ),
        migrations.CreateModel(
            name='TrainerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст ответа')),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='lessons.trainer', verbose_name='Тренажер')),
            ],
            options={
                'verbose_name': 'Ответ для тренажера',
                'verbose_name_plural': 'Ответы для тренажеров',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.SlugField(help_text='Если Вы хотите получить URL-адрес вида https://domain/page, тогда просто введите page.', max_length=128, unique=True, verbose_name='Название страницы в URL')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research', related_query_name='research', to='lessons.unit', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', related_query_name='lesson', to='lessons.unit', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст ответа')),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='lessons.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Ответ для игры',
                'verbose_name_plural': 'Ответы для игры',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', related_query_name='game', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.CreateModel(
            name='AddMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lessons/add_material', verbose_name='Изображение доп. материала')),
                ('url', models.URLField(help_text='Введите полный URL-адрес ресурса.', verbose_name='URL-адрес')),
                ('name', ckeditor.fields.RichTextField(max_length=128, verbose_name='Название доп. материала')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_materials', related_query_name='add_material', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Дополнительный материал',
                'verbose_name_plural': 'Дополнительные материалы',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides', verbose_name='Изображение слайда')),
                ('delay', models.PositiveIntegerField(help_text='В секундах.', verbose_name='Время показа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', related_query_name='slide', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'order_with_respect_to': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='PracticalTaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lessons/practical_tasks', verbose_name='Изоражение')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_steps', related_query_name='practical_step', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Шаг практического задания',
                'verbose_name_plural': 'Практическое задание',
                'order_with_respect_to': 'lesson',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='unit',
        ),
    ]
