# Generated by Django 4.0.5 on 2022-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='researches/background', verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='serial_number',
            field=models.CharField(help_text='Порядковый номер вида "1-2".', max_length=32, verbose_name='Порядковый номер'),
        ),
    ]
