# Generated by Django 4.0.5 on 2022-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='practical_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название практического задания'),
        ),
    ]
