# Generated by Django 4.0.5 on 2022-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/game', verbose_name='Первое изображение для игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/game', verbose_name='Второе изображение для игры'),
        ),
    ]
