# Generated by Django 4.0.5 on 2022-06-09 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_practical_title'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='unit',
        ),
    ]
