# Generated by Django 4.0.5 on 2022-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_game_first_image_alter_game_second_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='fact_img',
            field=models.ImageField(default='asdfasdf', upload_to='lessons/fact', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='fact_text',
            field=models.TextField(default='asdfasdf', max_length=4096, verbose_name='Текст'),
        ),
    ]
