# Generated by Django 4.0.5 on 2022-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_unit_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядковый номер'),
        ),
    ]
