# Generated by Django 4.0.5 on 2022-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_fact_img_lesson_fact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fact_img',
            field=models.ImageField(upload_to='lessons/fact', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='fact_text',
            field=models.TextField(max_length=4096, verbose_name='Текст'),
        ),
    ]
