# Generated by Django 4.0.5 on 2022-06-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_research_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.PositiveIntegerField(help_text='Этот параметр определяет позицию раздела среди всех разделов.', unique=True, verbose_name='Порядковый номер'),
        ),
    ]
