# Generated by Django 4.0.5 on 2022-06-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', related_query_name='lesson', to='lessons.unit', verbose_name='Раздел'),
        ),
    ]
