# Generated by Django 4.0.5 on 2022-06-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_fact_img_alter_lesson_fact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='interesting_img',
            field=models.ImageField(upload_to='lessons/interesting', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='interesting_text',
            field=models.TextField(max_length=4096, verbose_name='Текст'),
        ),
    ]
