# Generated by Django 4.0.5 on 2022-06-09 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_materials', related_query_name='add_material', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='game',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', related_query_name='game', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='practicaltaskstep',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_steps', related_query_name='practical_step', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='research',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research', related_query_name='research', to='lessons.unit', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', related_query_name='slide', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', related_query_name='trainer', to='lessons.lesson', verbose_name='Урок'),
        ),
    ]
