# Generated by Django 4.0.5 on 2022-06-17 09:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Отображается под заголовком и над главным изображением.', null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages', verbose_name='Главное изображение'),
        ),
    ]
