# Generated by Django 4.0.5 on 2022-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_staticpage_subtitle_alter_staticpage_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='in_footer',
            field=models.BooleanField(default=False, help_text='Заголовок страницы будет отображаться в футере сайта.', verbose_name='В футер'),
        ),
    ]
