# Generated by Django 4.0.5 on 2022-06-04 14:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент страницы')),
                ('date_last_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Статичная страница',
                'verbose_name_plural': 'Статичные страницы',
            },
        ),
    ]
